name: Build with cmake

on:
  push:
    branches: [master]
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu (${{ matrix.compiler.cc }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {cc: gcc, cxx: g++}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update apt
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install --yes cmake libsdl1.2-dev libsdl-ttf2.0-dev libsdl-image1.2-dev

      - name: cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ github.workspace }}/build
          cc: ${{ matrix.compiler.cc }}
          cxx: ${{ matrix.compiler.cxx }}
          build-type: Release
          parallel: 2
